# Crowdin Configuration
# This file configures automatic sync between Crowdin and this GitHub repo
# See: https://support.crowdin.com/github-integration/

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /templates/en.json
    translation: /messages/%locale%.json
